### ISSUE TITLE
Bloomberg SWE New Grad

### ISSUE THREAD

**Issue by quantumscholar** [speedyapply/2025-SWE-College-Jobs#10]
### Position Title

2025 Software Engineer

### Position Application Link

https://bloomberg.avature.net/careers/JobDetail/2025-Software-Engineer-New-York/6961

### Company Name

Bloomberg

### Company Link

bloomberg.com

### Location

New York, NY

### Is this a new grad position or an internship?

New Grad

### Is this position based in the USA?

Yes, it's based in the USA.

**Comment by kirkwat** [comment]
Good find. Thank you! @quantumscholar
