### ISSUE TITLE
Bloomberg New Grad SWE

### ISSUE THREAD

**Issue by quantumscholar** [speedyapply/2025-SWE-College-Jobs#11]
### Position Title

New Grad Software Engineer

### Position Application Link

 https://bloomberg.avature.net/careers/JobDetail/2025-Software-Engineer-New-York/6961

### Company Name

Bloomberg

### Company Link

bloomberg.com

### Location

New York, NY

### Is this a new grad position or an internship?

New Grad

### Is this position based in the USA?

Yes, it's based in the USA.

**Comment by kirkwat** [comment]
this job was added to [NEW_GRAD_USA.md](https://github.com/speedyapply/2025-SWE-College-Jobs/blob/main/NEW_GRAD_USA.md) in the first issue that you opened. it was added in this [commit](https://github.com/speedyapply/2025-SWE-College-Jobs/commit/f6fba7839091f54b198f16921e1abc1f87cd3d53) along with others. was there a different link you meant to attach?
- #10 
![image](https://github.com/user-attachments/assets/6e485139-88e0-4c2f-8b80-49772709beca)
