### ISSUE TITLE
Software Engineer Intern

### ISSUE THREAD

**Issue by Mohamed-khaled0** [speedyapply/2025-SWE-College-Jobs#12]
### Position Title

Software Engineer Intern

### Position Application Link

https://www.glassdoor.com/Job/us-software-engineer-intern-jobs-SRCH_IL.0,2_IN1_KO3,27.htm

### Company Name

Four Hands 

### Company Link

https://careers.fourhands.com/postings/4e27cc81-52ce-4f65-b25c-9106b781b74d?utm_medium=job_board&utm_source=indeed

### Location

Austin, TX

### Is this a new grad position or an internship?

Internship

### Is this position based in the USA?

Yes, it's based in the USA.

### Your GitHub Email

mohamedalshraby3@gmail.com

**Comment by cullenwatson** [comment]
should be one job in one issue
