### ISSUE TITLE
Software Dev Engineer Intern 2025, Automated Reasoning

### ISSUE THREAD

**Issue by Mohamed-khaled0** [speedyapply/2025-SWE-College-Jobs#13]
### Position Title

Software Dev Engineer Intern 2025

### Position Application Link

https://www.glassdoor.com/Job/us-software-engineer-intern-jobs-SRCH_IL.0,2_IN1_KO3,27.htm

### Company Name

Amazon.com Services LLC

### Company Link

https://www.amazon.jobs/en/jobs/2798104/software-dev-engineer-intern-2025-automated-reasoning?cmpid=DA_INAD200785B

### Location

Seattle, WA

### Is this a new grad position or an internship?

Internship

### Is this position based in the USA?

No, it's international.

### Your GitHub Email

mohamedalshraby3@gmail.com

**Comment by cullenwatson** [comment]
should be one job in one issue
