### ISSUE TITLE
Software Engineering Positions at MathWork

### ISSUE THREAD

**Issue by nothans** [speedyapply/2025-SWE-College-Jobs#15]
### Position Title

Software Engineer

### Position Application Link

https://www.mathworks.com/company/jobs/opportunities/16217-multiple-openings-engineering-development-group-u-s?source=19812&s_eid=Rci_19812

### Company Name

MathWorks

### Company Link

https://www.mathworks.com

### Location

Natick, MA

### Is this a new grad position or an internship?

New Grad

### Is this position based in the USA?

Yes, it's based in the USA.

### Your GitHub Email

hscharler@gmail.com

**Comment by nothans** [comment]
Thanks for the approval. How do I fix the issue with the action?

**Comment by kirkwat** [comment]
Hey, that's actually an issue on our end. Fixing it now

**Comment by kirkwat** [comment]
Thank you for the contribution @nothans
